### ISSUE TITLE
Question: why external rate is being used for calculating profit on base_currency:currency trade?

### ISSUE THREAD

**Issue by bitfag** [probstj/ccGains#12]
I'm reviewing the library to understand whether it fits for my task of analyzing history of a trading strategy. I found some strange thing which I want to clarify.

In bags.py `pay()` method uses rate obtained from `self.relation.get_rate()` which is some historical data obtained from an exchange. It looks fine for processing non-base_currency trades (BTC:ALTCOIN markets), but it's looks strange for trades involving base_currency (BTC:USD). For such trade you can clearly see what amount of base currency was obtained by selling asset just from trade transaction, you don't need to refer to some external average rate for that. Furthermore, such method can influence "Proceeds" giving slightly different amounts of base currency which will be not equal to really obtained amount.

Though I see that detailed report actually uses real sell price for rendering first line (Sold xxx BTC for xxx BASE) `{% set buy_amount = sale.buy_ratio * sale.to_pay %}`, but all "proceeds", "total taxable gain" etc uses rate-derived base asset amounts.

I want to understand why such behavior was implemented, maybe I'm missing something? I actually needed to analyze trading history on XXX:YYY market and I was surprised why I cannot do that just by using trade history data only.

**Comment by probstj** [comment]
You are completely right, that didn't make much sense. Thanks a lot for pointing it out! Did the fix properly address this issue?

**Comment by bitfag** [comment]
Thanks, the fix looks good!
