### ISSUE TITLE
Support for swapping coin ticker names

### ISSUE THREAD

**Issue by anson-vandoren** [probstj/ccGains#9]
There are some coins that have changed ticker symbols. One example is AntShares(ANS) -> NEO (NEO) which happened in 2017. Most exchanges updated their historical pricing data to reflect the new trading pair (e.g. NEO/BTC instead of ANS/BTC), so it is not possible to get pricing data.

I think the easiest way to correct for issues like this (there are a few other examples I know of besides just ANS/NEO) would be to update the ticker symbol on ingestion, but I could see some reasons to not do that, and instead create a second currency relation (e.g. pull NEO/BTC data, but rename it to ANS/BTC).

I would like to add a optional argument in the form of a dict {'old ticker': 'new ticker'}, but would appreciate suggestions on where it makes the most sense to implement this.

**Comment by probstj** [comment]
I think your solution is very clean, since nothing is done automatically which could potentially surprise users. They must explicitly call the new function if they have traded such coins, then they will be aware of the name change issue anyway.

> but I could see some reasons to not do that
care to elaborate? Still see some reasons?

**Comment by anson-vandoren** [comment]
My only concern with this is that I don't know for sure how all possible data sources handle coin name changes. My two data points for this are Bittrex and Binance, both in relation to the ANS/NEO name change. In those two cases, the exchanges updated their pricing history to reflect the two names.

I am not sure how other exchanges would treat it, and it is possible that some would still retain the original ticker name up to the point where it changed, and then have a different ticker pair after that.

Anyway, since it is optional and not automatic, I would assume that a user has verified their data sources before calling this, and is sure they want to make the change. I would be open in the future to re-thinking how this is implemented if a new user with a new data source finds this conflicts with their desired inputs, but for now I think it should be fine.

**Comment by probstj** [comment]
OK, I understand and agree fully. 

I think I can close this now, thanks to your pull request. Thanks again :)
